# Generated by Django 2.0.13 on 2019-04-27 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Foodtruck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truckname', models.CharField(max_length=200)),
                ('truckplace', models.CharField(max_length=200)),
                ('truckphoto', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuname', models.CharField(max_length=200)),
                ('menuprice', models.CharField(max_length=200)),
                ('foodtruck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodtruck.Foodtruck')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='foodtruck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodtruck.Foodtruck'),
        ),
    ]
