# Generated by Django 2.0.13 on 2019-04-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0002_auto_20190427_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtruck',
            name='truckinfo',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
