# Generated by Django 2.0.13 on 2019-04-27 17:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HitCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default=None, max_length=15, null=True)),
                ('date', models.DateField(blank=True, default=datetime.datetime(2019, 4, 27, 17, 39, 38, 689483, tzinfo=utc), null=True)),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booth.Booth')),
            ],
        ),
    ]
