# Generated by Django 2.0.13 on 2019-05-12 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hitcount',
            name='booth',
        ),
        migrations.DeleteModel(
            name='HitCount',
        ),
    ]
