# Generated by Django 2.0.13 on 2019-05-12 08:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='checkbooth',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='hitcount',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 5, 12, 8, 12, 43, 662261, tzinfo=utc), null=True),
        ),
    ]
