# Generated by Django 2.0.13 on 2019-05-12 08:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0002_auto_20190512_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='checkbooth',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hitcount',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 5, 12, 8, 13, 35, 850657, tzinfo=utc), null=True),
        ),
    ]
