# Generated by Django 2.1.5 on 2019-05-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0002_auto_20190513_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image',
        ),
        migrations.AddField(
            model_name='photo',
            name='imagelink',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
