# Generated by Django 2.1.5 on 2019-05-14 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0003_auto_20190515_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='imagelink',
            new_name='image',
        ),
    ]
