# Generated by Django 2.0.13 on 2019-05-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
