# Generated by Django 2.0.13 on 2019-05-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_question_imagelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='imagelink',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
