# Generated by Django 2.0.13 on 2019-05-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_award_imagelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='imagelink',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
