# Generated by Django 2.0.13 on 2019-05-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20190513_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='imagelink',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
